// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx6jMNXm8DdOllcOJExued3ZTdeCKuGHc',
    appId: '1:483878763852:android:178b150e384d6d8293a3e9',
    messagingSenderId: '483878763852',
    projectId: 'weatherapp-427f6',
    authDomain: 'insightacademia-747dc.firebaseapp.com',
    storageBucket: 'weatherapp-427f6.appspot.com',
    measurementId: 'G-6W4K7QG44B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx6jMNXm8DdOllcOJExued3ZTdeCKuGHc',
    appId: '1:483878763852:android:178b150e384d6d8293a3e9',
    messagingSenderId: '483878763852',
    projectId: 'weatherapp-427f6',
    storageBucket: 'weatherapp-427f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx6jMNXm8DdOllcOJExued3ZTdeCKuGHc',
    appId: '1:483878763852:android:178b150e384d6d8293a3e9',
    messagingSenderId: '483878763852',
    projectId: 'weatherapp-427f6',
    storageBucket: 'weatherapp-427f6.appspot.com',
    iosBundleId: 'com.example.assignmentclimateapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx6jMNXm8DdOllcOJExued3ZTdeCKuGHc',
    appId: '1:483878763852:android:178b150e384d6d8293a3e9',
    messagingSenderId: '483878763852',
    projectId: 'weatherapp-427f6',
    storageBucket: 'weatherapp-427f6.appspot.com',
    iosBundleId: 'com.example.assignmentclimateapp.RunnerTests',
  );
}
